name: Optimize resource pack
on:
  push:
    tags:
      - "v*"
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash (waepack)
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'waepack'
            output_file_path = '/tmp/waepack-${{ github.ref_name }}.zip'
            allow_mods = ['OptiFine']
          artifact_name: 'waepack-${{ github.ref_name }}.zip'
      - name: Run PackSquash (waepack-models)
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'waepack-models'
            output_file_path = '/tmp/waepack-models-${{ github.ref_name }}.zip'
          artifact_name: 'waepack-models-${{ github.ref_name }}.zip'
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/waepack-${{ github.ref_name }}.zip
            /tmp/waepack-models-${{ github.ref_name }}.zip
